### ISSUE TITLE
如何指定默认选中值

### ISSUE THREAD

**Issue by dashu110** [the-nippy/react-native-slidepicker#11]
你好, 如何指定  ParallelPicker 的默认值? 
例如
` <ParallelPicker 
    dataSource={ [ [ {'name': 1},  {'name': 2},  {'name': 3},  {'name': 4},  {'name': 5}, ]]}`

想要默认选中 name : 3

**Comment by the-nippy** [comment]
你好，更新到 v1.1.2，ParallelPicker 可使用 defaultValueIndexes 属性，`defaultValueIndexes = {[2]}` 表示选中第三个
