### ISSUE TITLE
RNGestureHandlerRootView没有被加载，不知道咋回事

### ISSUE THREAD

**Issue by buloo** [the-nippy/react-native-slidepicker#14]
java.lang.IllegalStateException: View com.swmansion.gesturehandler.react.RNGestureHandlerRootView{6064e64 V.E...... ......ID 0,0-1080,690 #47b} has not been mounted under ReactRootView
        at com.swmansion.gesturehandler.react.RNGestureHandlerRootHelper.findRootViewTag(RNGestureHandlerRootHelper.java:35)
        at com.swmansion.gesturehandler.react.RNGestureHandlerRootHelper.<init>(RNGestureHandlerRootHelper.java:51)
        at com.swmansion.gesturehandler.react.RNGestureHandlerRootView.onAttachedToWindow(RNGestureHandlerRootView.java:26)

**Comment by lexguy** [comment]
需要手动安装这个依赖（我完善一下文档）
`npm install react-native-gesture-handler`
，有安装这个依赖吗，RN0.60版本前后依赖有区别，参照这个库文档安装引用一下。

**Comment by the-nippy** [comment]
> java.lang.IllegalStateException: View com.swmansion.gesturehandler.react.RNGestureHandlerRootView{6064e64 V.E...... ......ID 0,0-1080,690 #47b} has not been mounted under ReactRootView
> at com.swmansion.gesturehandler.react.RNGestureHandlerRootHelper.findRootViewTag(RNGestureHandlerRootHelper.java:35)
> at com.swmansion.gesturehandler.react.RNGestureHandlerRootHelper.(RNGestureHandlerRootHelper.java:51)
> at com.swmansion.gesturehandler.react.RNGestureHandlerRootView.onAttachedToWindow(RNGestureHandlerRootView.java:26)

需要手动安装这个依赖（我完善一下文档）
npm install react-native-gesture-handler
，有安装这个依赖吗，RN0.60版本前后依赖有区别，参照这个库文档安装引用一下。

**Comment by buloo** [comment]
> > java.lang.IllegalStateException: View com.swmansion.gesturehandler.react.RNGestureHandlerRootView{6064e64 V.E...... ......ID 0,0-1080,690 #47b} has not been mounted under ReactRootView
> > at com.swmansion.gesturehandler.react.RNGestureHandlerRootHelper.findRootViewTag(RNGestureHandlerRootHelper.java:35)
> > at com.swmansion.gesturehandler.react.RNGestureHandlerRootHelper.(RNGestureHandlerRootHelper.java:51)
> > at com.swmansion.gesturehandler.react.RNGestureHandlerRootView.onAttachedToWindow(RNGestureHandlerRootView.java:26)
> 
> 需要手动安装这个依赖（我完善一下文档）
> npm install react-native-gesture-handler
> ，有安装这个依赖吗，RN0.60版本前后依赖有区别，参照这个库文档安装引用一下。

我们是混合开发，在安卓项目里直接加载打包好的jsbundle。autolink可能不起作用。

**Comment by the-nippy** [comment]
> > > java.lang.IllegalStateException: View com.swmansion.gesturehandler.react.RNGestureHandlerRootView{6064e64 V.E...... ......ID 0,0-1080,690 #47b} has not been mounted under ReactRootView
> > > at com.swmansion.gesturehandler.react.RNGestureHandlerRootHelper.findRootViewTag(RNGestureHandlerRootHelper.java:35)
> > > at com.swmansion.gesturehandler.react.RNGestureHandlerRootHelper.(RNGestureHandlerRootHelper.java:51)
> > > at com.swmansion.gesturehandler.react.RNGestureHandlerRootView.onAttachedToWindow(RNGestureHandlerRootView.java:26)
> > 
> > 
> > 需要手动安装这个依赖（我完善一下文档）
> > npm install react-native-gesture-handler
> > ，有安装这个依赖吗，RN0.60版本前后依赖有区别，参照这个库文档安装引用一下。
> 
> 我们是混合开发，在安卓项目里直接加载打包好的jsbundle。autolink可能不起作用。

那生成jsbunble的项目有安装这个react-native-gesture-handler吗，是否能正确引用，正常地运行？要确保打好的jsbundle的代码是正确引用的呀

**Comment by buloo** [comment]
> > > > java.lang.IllegalStateException: View com.swmansion.gesturehandler.react.RNGestureHandlerRootView{6064e64 V.E...... ......ID 0,0-1080,690 #47b} has not been mounted under ReactRootView
> > > > at com.swmansion.gesturehandler.react.RNGestureHandlerRootHelper.findRootViewTag(RNGestureHandlerRootHelper.java:35)
> > > > at com.swmansion.gesturehandler.react.RNGestureHandlerRootHelper.(RNGestureHandlerRootHelper.java:51)
> > > > at com.swmansion.gesturehandler.react.RNGestureHandlerRootView.onAttachedToWindow(RNGestureHandlerRootView.java:26)
> > > 
> > > 
> > > 需要手动安装这个依赖（我完善一下文档）
> > > npm install react-native-gesture-handler
> > > ，有安装这个依赖吗，RN0.60版本前后依赖有区别，参照这个库文档安装引用一下。
> > 
> > 
> > 我们是混合开发，在安卓项目里直接加载打包好的jsbundle。autolink可能不起作用。
> 
> 那生成jsbunble的项目有安装这个react-native-gesture-handler吗，是否能正确引用，正常地运行？要确保打好的jsbundle的代码是正确引用的呀

安装了，版本是1.5.3。因为太低了？。

**Comment by the-nippy** [comment]
先跑起来，再检查依赖
