### ISSUE TITLE
modal内无法滚动

### ISSUE THREAD

**Issue by shenxingchao** [the-nippy/react-native-slidepicker#17]
- 描述
  react-native-modal内无法滚动，绝对定位View里面可以，modal换了2个了
- 代码如下
  ```javascript
  <Modal
    isVisible={show}
    backdropColor={'#000'}
    backdropOpacity={0.6}
    backdropTransitionOutTiming={0}
    style={{ flex: 1, margin: 0, justifyContent: 'flex-end' }}
  >
    <CascadePicker
      dataSource={data_json}
      headOptions={{
        backgroundColor: ThemeColor.primary,
        confirmText: '确认',
        cancelText: '取消',
        confirmStyle: { color: ThemeColor.white },
        cancelStyle: { color: ThemeColor.white }
      }}
      cancel={() => {
        setShow(false)
      }}
      confirm={data => {
        console.log(data)
        setShow(false)
      }}
      pickerStyle={{
        visibleNum: 4,
        itemHeight: 60,
        activeBgColor: ThemeColor.white,
        activeBgOpacity: 1,
        activeFontSize: 18,
        activeFontColor: ThemeColor.h1,
        normalBgColor: ThemeColor.white,
        normalBgOpacity: 1,
        normalFontSize: 16,
        normalFontColor: ThemeColor.h3,
  
        activeFontSize: 18,
        zIndex: 9999999
      }}
    />
  </Modal>
  ```
- 运行效果如下
  ![](https://github.com/shenxingchao/react-native-job/blob/master/demo2.gif?raw=true)

**Comment by the-nippy** [comment]
提供一下react-native，react-native-modal，以及react-native-gesture-handler版本号，我复现一下
另外可以尝试一下我的 Example 里面的例子能不能运行起来，也是 react-native-modal 来做的  @shenxingchao

**Comment by shenxingchao** [comment]
```
"react-native": "0.63.4",
"react-native-modal": "^11.7.0",
"react-native-gesture-handler": "^1.10.1",
```
@lexguy 好的，我去运行下例子

**Comment by shenxingchao** [comment]
我跑了例子 没问题，然后我在我的项目里运行出现了问题，发现是将组件放入react-navigation 堆栈组件就不能滑动
react-navigation 组件如下 
```
 "@react-navigation/native": "^5.9.2",
 "@react-navigation/stack": "^5.14.2",
```
可以
```javascript
<NavigationContainer>
  <Picker />
</NavigationContainer>
```
不行
```javascript
import React from 'react'
//导入导航容器
import { NavigationContainer } from '@react-navigation/native'
//导入堆栈导航容器
import { createStackNavigator } from '@react-navigation/stack'
//创建堆栈导航
const Stack = createStackNavigator()

import Picker  from './Picker '

let App = () => {
  return (
    <NavigationContainer>
      <Stack.Navigator initialRouteName="HomeScreen">
        <Stack.Screen
          name="HomeScreen"
          component={Picker}
        />
      </Stack.Navigator>
    </NavigationContainer>
  )
}

export default App
```

**Comment by the-nippy** [comment]
react-navigation 和这个rn-slidepicker 都用到了 react-native-gesture-handler，react-native-modal 的层级也很高，手势应该是被捕获了。可以参考一下讨论:
 - <a href="https://github.com/software-mansion/react-native-gesture-handler/issues/139">react-native-gesture-handler/issues/139</a>
 - [react-native-gesture-handler/pull/937](https://github.com/software-mansion/react-native-gesture-handler/pull/937)


讨论里暂时可行的方案是给 `Modal` 设置 `coverScreen={false}`  属性，可以恢复滑动。

不过这样会导致一个问题，组件在层级较深的时候不能覆盖全屏。对于这种情况，可以将`Modal`封装一次，放在组件树中相对顶部的位置来设置全屏覆盖样式，自定义`Modal`组件后通过设置`Ref`来命令式的设置`Children`。

这都是曲线救国的方案，没有真正解决问题，更好的方案还需要跟进和研究   @shenxingchao

**Comment by shenxingchao** [comment]
好的 我用 [react-native-picker](https://github.com/beefe/react-native-picker) 测试出来是可以滚动的 ，继续关注😀

**Comment by DreamTravelingLight** [comment]
同样的情况，请问现在有解决办法吗，上面试用coverScreen={false}也不能滚动

**Comment by the-nippy** [comment]
1.x 的版本上使用的是 react-native-gesture-handler ， 配合 react-native-modal 的时候会有一些问题。https://github.com/software-mansion/react-native-gesture-handler/issues/139

2.x 的版本已放弃使用 react-native-gesture-handler , 改用 RN 组件 flatlist 实现，对弹出层目前使用的是绝对定位的View，欢迎使用和 issue 哈 ～
