### ISSUE TITLE
安卓无法滑动

### ISSUE THREAD

**Issue by yushuangxu** [the-nippy/react-native-slidepicker#19]
在ios可以滑动 但是在安卓里面滑不动

**Comment by lexguy** [comment]
好，问题应该是和genture-handler库的兼容处理问题导致的，最近有打算纯JS实现，感谢关注~

**Comment by the-nippy** [comment]
> 在ios可以滑动 但是在安卓里面滑不动


好，问题应该是和genture-handler库的兼容处理问题导致的，最近有打算纯JS实现，感谢关注~

**Comment by lexguy** [comment]
> 
hello，我测试了API 32的机子可以正常滑动。可以提供一下你的Android版本号吗

**Comment by the-nippy** [comment]
> 在ios可以滑动 但是在安卓里面滑不动

hello，我测试了API 32的机子可以正常滑动。可以提供一下你的Android版本号吗

**Comment by the-nippy** [comment]
1.x 的版本上使用的是 react-native-gesture-handler ， 配合 react-native-modal 的时候会有一些问题。https://github.com/software-mansion/react-native-gesture-handler/issues/139

2.x 的版本已放弃使用 react-native-gesture-handler , 改用 RN 组件 flatlist 实现，对弹出层目前使用的是绝对定位的View，欢迎使用和 issue 哈 ～
