### ISSUE TITLE
change事件里面改值以后不生效会被重置

### ISSUE THREAD

**Issue by seventeen-eleven** [the-nippy/react-native-slidepicker#20]
componentDidUpdate(prevProps) {
    if (prevProps.list !== this.props.list) {
      this.transValue.setValue(0);
      this.dataBack(0);
    }
  }

设置以后没有更新最新的值 每次都会执行这个 把值还原为最初是的值，建议修改一下

**Comment by the-nippy** [comment]
> componentDidUpdate(prevProps) { if (prevProps.list !== this.props.list) { this.transValue.setValue(0); this.dataBack(0); } }
> 
> 设置以后没有更新最新的值 每次都会执行这个 把值还原为最初是的值，建议修改一下

是的，现在是没有值回显的效果。这个修改涉及到每次选上一层的值之后需要重置下一层的初始值这个逻辑， 正在修改中，感谢建议~

**Comment by the-nippy** [comment]
更新到v1.2.0处理了数据回显的问题，不会有还原最初的值的问题了
