### ISSUE TITLE
选择器数据返回问题

### ISSUE THREAD

**Issue by shuaigeek** [the-nippy/react-native-slidepicker#21]
大佬你好，最近项目需要一个滑动选择器组件，看到你的库，运行起来效果很好，但是我遇到一点问题。
选择器点击确定后数据返回问题：传进选择器的数据是最新的，但是点击确定之后，返回的数据是上一次的，操作几次之后发现，需要先至少滚动到第二项，再选择数据，才能正常选择数据。

开发环境是：RN 0.66.4
测试手机：红米k20pro、Android11

**Comment by shuaigeek** [comment]
解决了，大佬组件设计的思路很好，但是跟我实际的业务需求有点不太一样，我修改了你一些代码，谢谢大佬提供的库

**Comment by the-nippy** [comment]
好的，非常感谢关注和代码提供。中间看到了你的评论又忙忘了没有及时回复，我看你后面怎么关闭了PR🤣--    发自新浪邮箱客户端
在 3月15日 11:26，b00l ***@***.***> 写道：


解决了，大佬组件设计的思路很好，但是跟我实际的业务需求有点不太一样，我修改了你一些代码，谢谢大佬提供的库



&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
