### ISSUE TITLE
value字段有值后,没有回显数据,

### ISSUE THREAD

**Issue by 007jiang7442262** [the-nippy/react-native-slidepicker#22]
### 版本号:
"react-native-slidepicker": "^1.2.0",
"react-native": "0.68.1",

### 代码:
import * as React from 'react';
import { Component } from 'react';
import { View, Modal } from 'react-native'
import { CascadePicker } from 'react-native-slidepicker';

export default class PickerTest extends Component<any, any> {
  state = { value: null }
  cancel = data => {
    this.props.hiedPicker();
  };
  
  confirm = data => {
    this.setState({ value: data });
    this.props.hiedPicker();
  };
  render() {
    return (
      <Modal transparent={true} animationType={'slide'} visible={this.props.showPicker} onRequestClose={() => { }}>
        <View style={{ flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.5)' }}>
          <CascadePicker
            value={this.state.value}
            dataSource={ParaData}
            cancel={this.cancel}
            confirm={this.confirm}
            headOptions={{
              confirmText: "确定",
              cancelText: "取消",
              itemHeight: "请选择城市",
            }}
          />
        </View>
      </Modal>

    );
  }
}

### 数据:
const ParaData = [
  {
    "name": "Asia",
    "id": 1,
    "list": [
      {
        "name": "China",
        "id": 100,
        "list": [
          {
            "name": "Beijing",
            "id": 1101
          }
        ]
      },
      {
        "name": "South Korea",
        "id": 200,
        "list": []
      }
    ]
  },
  {
    "name": "Asia1",
    "id": 2,
    "list": [
      {
        "name": "China2",
        "id": 200,
        "list": [
          {
            "name": "Beijing3",
            "id": 3101
          }
        ]
      },
      {
        "name": "South Korea4",
        "id": 400,
        "list": []
      }
    ]
  }
]

### 问题描写
我选择了Asia1,我再次打开的时候, 它有默认选择了Asia;

**Comment by the-nippy** [comment]
已更新2.0版本，对数据回显和选中处理～
