### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by tyawei** [the-nippy/react-native-slidepicker#25]
1. ts 和参数类型声明缺失。看源码没有ts，也没有规定props的参数类型；
2. dataSource 数据结构不常规，限制太死，id  name 是必传的，整个是一个二维数组，最常规的[{...}, {...}]其实应该可以；建议采用 FlatList 的renderItem，自定义渲染列表item；
3. name 字段放在<Text> 里面，name 默认只能支持 string  name  <Text>  <Image>，不能支持<View> 嵌入去渲染更多的结构；
4. console.log   console.warn ，建议只在__DEV__出现

**Comment by the-nippy** [comment]
更新 v2.0 版本
1. 其中添加部分 ts 类型
2. dataSource 中的具体字段总是要指定的，最少保留一个value，动态字段名暂时没有去兼容。组件已采用 flatlist 实现，把 renderItem 整个暴露出来的话自由度就很高了，后续可以考虑

感谢建议～  💕
